spring:
  profiles:
    active: "production"
---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/agilepays
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  data:
    rest:
      base-path: /api
      default-media-type: application/json
---
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://postgresql:5432/agilepays
    username: admin
    password: 123456
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  data:
    rest:
      base-path: /api
      default-media-type: application/json
      
        
